### ISSUE TITLE
Support for aurelia 1

### ISSUE THREAD

**Issue by talamaska** [aurelia/vscode-extension#154]
**I'm submitting a feature request**

* **Extension Version:**
v2.0.6

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Visual studio code version:**
1.54.3

* **What is the expected behavior?**
I would like a config or other extension that still supports aurelia 1.

* **What is the motivation / use case for changing the behavior?**
My project can't be migrated. Yesterday everything was fine, today the plugin is updated and my vs code is getting crazy of showing errors in the notifications and spams the output tab. I didn't want that. This breaks my dev environment

**Comment by hiaux0** [comment]
I'm sorry you have to experience this.

My first suggestion would be to install the latest "stable" version, then choose `1.0.7`
![image](https://user-images.githubusercontent.com/30693990/111888330-db98cf00-89db-11eb-9010-3711ad8e9242.png)

Besides that, the highest priority for the extension right now is to make it as low configurable as possible.
(Currently, you need a `tsconfig.json` file)
For that, it would be helpful, if you could share some more info about your project structure.
- aurelia cli generated
- monorepo
- pure js

**Comment by hiaux0** [comment]
> updated and my vs code is getting crazy of showing errors in the notifications and spams the output tab. I didn't want that. This breaks my dev environment

> updated and my vs code is getting crazy of showing errors in the notifications 

Could you share some screenshots of the output?
v2.0.6 actually tried to make the error go silent, so unless, there is a path to tsconfig specified, this should be only thing the extension outputs
![image](https://user-images.githubusercontent.com/30693990/111888461-09324800-89dd-11eb-8b46-8aed55bed053.png)

> and spams the output tab. 

Should prob. add a "verbose" setting. Thx for bringing that up.

**Comment by hiaux0** [comment]
> today the plugin is updated

From which version did you update to 2.0.6?

**Comment by talamaska** [comment]
I haven't looked from which version.

**Comment by talamaska** [comment]
![image](https://user-images.githubusercontent.com/299973/112164696-c481f900-8bf6-11eb-82ca-26cfe5368053.png)
 Here it is. On 2.0.6 editing an html in <template>

**Comment by hiaux0** [comment]
> Here it is. On 2.0.6 editing an html in

Thx for following up with examples!

1. To better help you, can you provide a screenshot of the Output on startup?

![image](https://user-images.githubusercontent.com/30693990/112183226-56413480-8bfe-11eb-895f-1aa888e050a3.png)

2. You can find out, which components the extension picked up by 
(! Note, if you have too many components, it may print out nothing :(( )
- Open command palette (ctrl/cmd+shift+p)
- Type in `Developer: Toggle Developer Tools`
![image](https://user-images.githubusercontent.com/30693990/112183307-69ec9b00-8bfe-11eb-8012-4dd9aee0ab4f.png)
- Again in the command palette, the following Aurelia command:
`Aurelia: [Au] Show Aurelia Components parsed by the extension`
- Which should result in
![image](https://user-images.githubusercontent.com/30693990/112183717-cd76c880-8bfe-11eb-903f-a5dc21b82cbc.png)

3. If the component is missing in the collection, then I'll have to figure out why

**Comment by talamaska** [comment]
```
[server.ts] 1. onInitialize
[server.ts] 2. onInitialized
[server.ts] 3. Create Aurelia Watch Program
[Info] The Extension is based on this directly:  d:\www\navigator3-online
[INFO]: Path to tsconfig.json detected:
undefined
⚠⚠⚠
[WARNING] No tsconfig.json file found
You can manually specify a path to your tsconfig.json file by adding the following configs to your settings.json:
"aurelia.pathToTsConfig": "<path-to-config>"
⚠⚠⚠
[INFO] Furthermore, you can control, eg. the root directory, or includes/excludes.
Please check out the documentation to find out more
https://github.com/aurelia/vscode-extension#configuration
[server.ts] (re-)get Language Modes
[eb.ts] Starting document parsing
TCL: error TypeError: Cannot read property 'map' of undefined
    at c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\server\out\feature\embeddedLanguages\embeddedSupport.js:47:13
    at new Promise (<anonymous>)
    at parseDocumentRegions (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\server\out\feature\embeddedLanguages\embeddedSupport.js:35:12)
    at Object.<anonymous> (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\server\out\feature\embeddedLanguages\embeddedSupport.js:271:29)
    at Generator.next (<anonymous>)
    at c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\server\out\feature\embeddedLanguages\embeddedSupport.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\server\out\feature\embeddedLanguages\embeddedSupport.js:4:12)
    at Object.getDocumentRegions (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\server\out\feature\embeddedLanguages\embeddedSupport.js:268:12)
    at c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\server\out\feature\embeddedLanguages\languageModes.js:45:127
TCL: error TypeError: Cannot read property 'filter' of undefined
    at getRegionAtPosition (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\server\out\feature\embeddedLanguages\embeddedSupport.js:433:38)
    at Object.getRegionAtPosition (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\server\out\feature\embeddedLanguages\embeddedSupport.js:280:48)
    at Object.<anonymous> (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\server\out\feature\embeddedLanguages\languageModes.js:68:63)
    at Generator.next (<anonymous>)
    at fulfilled (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\server\out\feature\embeddedLanguages\languageModes.js:15:58)
[server.ts] (re-)get Language Modes
[server.ts] (re-)get Language Modes
[server.ts] (re-)get Language Modes
[eb.ts] Starting document parsing
TCL: error TypeError: Cannot read property 'map' of undefined
    at c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\server\out\feature\embeddedLanguages\embeddedSupport.js:47:13
    at new Promise (<anonymous>)
    at parseDocumentRegions (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\server\out\feature\embeddedLanguages\embeddedSupport.js:35:12)
    at Object.<anonymous> (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\server\out\feature\embeddedLanguages\embeddedSupport.js:271:29)
    at Generator.next (<anonymous>)
    at c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\server\out\feature\embeddedLanguages\embeddedSupport.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\server\out\feature\embeddedLanguages\embeddedSupport.js:4:12)
    at Object.getDocumentRegions (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\server\out\feature\embeddedLanguages\embeddedSupport.js:268:12)
    at c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\server\out\feature\embeddedLanguages\languageModes.js:45:127
[server.ts] (re-)get Language Modes
[server.ts] (re-)get Language Modes
[eb.ts] Starting document parsing
TCL: error TypeError: Cannot read property 'map' of undefined
    at c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\server\out\feature\embeddedLanguages\embeddedSupport.js:47:13
    at new Promise (<anonymous>)
    at parseDocumentRegions (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\server\out\feature\embeddedLanguages\embeddedSupport.js:35:12)
    at Object.<anonymous> (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\server\out\feature\embeddedLanguages\embeddedSupport.js:271:29)
    at Generator.next (<anonymous>)
    at c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\server\out\feature\embeddedLanguages\embeddedSupport.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\server\out\feature\embeddedLanguages\embeddedSupport.js:4:12)
    at Object.getDocumentRegions (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\server\out\feature\embeddedLanguages\embeddedSupport.js:268:12)
    at c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\server\out\feature\embeddedLanguages\languageModes.js:45:127
[server.ts] (re-)get Language Modes
[eb.ts] Starting document parsing
```

```

console.ts:137 [Extension Host] TCL: SearchDefinitionInView -> err Error: Request get-virtual-hover failed with message: Cannot read property 'filter' of undefined
	at handleResponse (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\node_modules\vscode-jsonrpc\lib\common\connection.js:477:48)
	at processMessageQueue (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\node_modules\vscode-jsonrpc\lib\common\connection.js:292:17)
	at Immediate.<anonymous> (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\node_modules\vscode-jsonrpc\lib\common\connection.js:276:13)
	at processImmediate (internal/timers.js:456:21)
console.ts:137 [Extension Host] TCL: SearchDefinitionInView -> err TypeError: Cannot read property 'lineAndCharacter' of null
	at SearchDefinitionInView.provideDefinition (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\out\extension.js:25:48)
31console.ts:137 [Extension Host] TCL: SearchDefinitionInView -> err Error: Request get-virtual-hover failed with message: Cannot read property 'filter' of undefined
	at handleResponse (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\node_modules\vscode-jsonrpc\lib\common\connection.js:477:48)
	at processMessageQueue (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\node_modules\vscode-jsonrpc\lib\common\connection.js:292:17)
	at Immediate.<anonymous> (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\node_modules\vscode-jsonrpc\lib\common\connection.js:276:13)
	at processImmediate (internal/timers.js:456:21)
console.ts:137 [Extension Host] TCL: SearchDefinitionInView -> err TypeError: Cannot read property 'lineAndCharacter' of null
	at SearchDefinitionInView.provideDefinition (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\out\extension.js:25:48)
8console.ts:137 [Extension Host] TCL: SearchDefinitionInView -> err Error: Request get-virtual-hover failed with message: Cannot read property 'filter' of undefined
	at handleResponse (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\node_modules\vscode-jsonrpc\lib\common\connection.js:477:48)
	at processMessageQueue (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\node_modules\vscode-jsonrpc\lib\common\connection.js:292:17)
	at Immediate.<anonymous> (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\node_modules\vscode-jsonrpc\lib\common\connection.js:276:13)
	at processImmediate (internal/timers.js:456:21)
2console.ts:137 [Extension Host] TCL: SearchDefinitionInView -> err TypeError: Cannot read property 'lineAndCharacter' of null
	at SearchDefinitionInView.provideDefinition (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\out\extension.js:25:48)
59console.ts:137 [Extension Host] TCL: SearchDefinitionInView -> err Error: Request get-virtual-hover failed with message: Cannot read property 'filter' of undefined
	at handleResponse (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\node_modules\vscode-jsonrpc\lib\common\connection.js:477:48)
	at processMessageQueue (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\node_modules\vscode-jsonrpc\lib\common\connection.js:292:17)
	at Immediate.<anonymous> (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\node_modules\vscode-jsonrpc\lib\common\connection.js:276:13)
	at processImmediate (internal/timers.js:456:21)
2console.ts:137 [Extension Host] TCL: SearchDefinitionInView -> err TypeError: Cannot read property 'lineAndCharacter' of null
	at SearchDefinitionInView.provideDefinition (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\out\extension.js:25:48)
12console.ts:137 [Extension Host] TCL: SearchDefinitionInView -> err Error: Request get-virtual-hover failed with message: Cannot read property 'filter' of undefined
	at handleResponse (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\node_modules\vscode-jsonrpc\lib\common\connection.js:477:48)
	at processMessageQueue (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\node_modules\vscode-jsonrpc\lib\common\connection.js:292:17)
	at Immediate.<anonymous> (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\node_modules\vscode-jsonrpc\lib\common\connection.js:276:13)
	at processImmediate (internal/timers.js:456:21)
console.ts:137 [Extension Host] TCL: SearchDefinitionInView -> err TypeError: Cannot read property 'lineAndCharacter' of null
	at SearchDefinitionInView.provideDefinition (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\out\extension.js:25:48)
2console.ts:137 [Extension Host] TCL: SearchDefinitionInView -> err Error: Request get-virtual-hover failed with message: Cannot read property 'filter' of undefined
	at handleResponse (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\node_modules\vscode-jsonrpc\lib\common\connection.js:477:48)
	at processMessageQueue (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\node_modules\vscode-jsonrpc\lib\common\connection.js:292:17)
	at Immediate.<anonymous> (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\node_modules\vscode-jsonrpc\lib\common\connection.js:276:13)
	at processImmediate (internal/timers.js:456:21)
console.ts:137 [Extension Host] TCL: SearchDefinitionInView -> err TypeError: Cannot read property 'lineAndCharacter' of null
	at SearchDefinitionInView.provideDefinition (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\out\extension.js:25:48)
12console.ts:137 [Extension Host] TCL: SearchDefinitionInView -> err Error: Request get-virtual-hover failed with message: Cannot read property 'filter' of undefined
	at handleResponse (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\node_modules\vscode-jsonrpc\lib\common\connection.js:477:48)
	at processMessageQueue (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\node_modules\vscode-jsonrpc\lib\common\connection.js:292:17)
	at Immediate.<anonymous> (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\node_modules\vscode-jsonrpc\lib\common\connection.js:276:13)
	at processImmediate (internal/timers.js:456:21)
console.ts:137 [Extension Host] TCL: SearchDefinitionInView -> err TypeError: Cannot read property 'lineAndCharacter' of null
	at SearchDefinitionInView.provideDefinition (c:\Users\Goldy\.vscode\extensions\aureliaeffect.aurelia-2.0.6\client\out\extension.js:25:48)
```

**Comment by hiaux0** [comment]
v2 currently relies on `tsconfig.json` (jsconfig.json needs to be configured, see below) being present.

Is your project a js project?
If yes, adding a `jsconfig.json` to the root will help to get this working.

1. Create an empty `jsconfig.json` in your root
2. In the settings do
```
{
  "aurelia.pathToTsConfig": "<absolute-path-to-jsconfig.json>"
}
```

I tested with an js project created by the aurelia-cli, and the default `app` component was detected.

Hope that helps!

**Comment by talamaska** [comment]
Yes it is a js based. Will try. Thanks.

**Comment by talamaska** [comment]
Ok it seems to work, but this absolute path cannot be stored in the workspace settings, because other people store their project in different folder.

**Comment by hiaux0** [comment]
> Ok it seems to work, but this absolute path cannot be stored in the workspace settings, because other people store their project in different folder.

"User" settings (as compared to "Workspace") should allow every developer to specify their path
![Uploading image.png…]()
