### ISSUE TITLE
Extension crashes in certain conditions

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aurelia/vscode-extension#194]
**I'm submitting a bug report**

* **Extension Version:**
v2.1.4

**Please tell us about your environment:**
* **Operating System:**
Windows 11

* **Visual studio code version:**
1.66.0

**Current behavior:**
The extension crashes under very strange circumstances. Try opening https://github.com/MaximBalaganskiy/extension-bug

```
[DocumentSettings] Exclude files based on globs (from setting: aureliaProject.exclude): 
[DocumentSettings]   **/node_modules, **/out, **/build, **/dist, aurelia_project
[DocumentSettings] Include files based on globs (from setting: aureliaProject.include): 
[DocumentSettings]   src
[initialization] Initilization started.
[AureliaProject] Found 1 package.json file(s):
[AureliaProject]   c:/Dev/au/extension-bug/package.json
[AureliaProject]   Searched in: **/package.json
[AureliaProject]   Excluded: **/node_modules, **/out, **/build, **/dist, aurelia_project
[AureliaProject] Found 1 Aurelia project(s) in: 
[AureliaProject]   c:\Dev\au\extension-bug
[AureliaProject] Parsing Aurelia related data...
[AureliaTsMorph] Including files based on: c:\Dev\au\extension-bug
c:\Dev\au\extension-bug\src\test.html
c:\Dev\au\extension-bug\src\subfolder
[initialization] Initilization done. Aurelia Extension is ready to use. 🚀 (took 337.1 ms)
node:fs:723
  handleErrorFromBinding(ctx);
  ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:723:3)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at Object.e.readFileSync (node:electron/js2c/asar_bundle:5:9148)
    at Function.createHtmlFromPath (c:\Users\maxim\.vscode\extensions\aureliaeffect.aurelia-2.1.4\server\out\common\documens\TextDocumentUtils.js:44:28)
    at c:\Users\maxim\.vscode\extensions\aureliaeffect.aurelia-2.1.4\server\out\core\viewModel\AureliaComponents.js:191:72
    at Array.forEach (<anonymous>)
    at AureliaComponents.enhanceWithViewRegions (c:\Users\maxim\.vscode\extensions\aureliaeffect.aurelia-2.1.4\server\out\core\viewModel\AureliaComponents.js:188:18)
    at AureliaComponents.init (c:\Users\maxim\.vscode\extensions\aureliaeffect.aurelia-2.1.4\server\out\core\viewModel\AureliaComponents.js:81:31)
    at AureliaProgram.initAureliaComponents (c:\Users\maxim\.vscode\extensions\aureliaeffect.aurelia-2.1.4\server\out\core\viewModel\AureliaProgram.js:26:32) {
  errno: -4068,
  syscall: 'read',
  code: 'EISDIR'
}
[Info  - 10:29:19 am] Connection to server got closed. Server will restart.
```

**Comment by hiaux0** [comment]
Interesting. I suspect there is wrong logic in reading files. It assumes a specific path or so.

ETA: Next monday
Note: you would have to manually download the .vsix file, as we have publishing issues right now

**Comment by hiaux0** [comment]
.vsix file here https://github.com/aurelia/vscode-extension/releases/tag/2.3.4

install
code --install-extension aurelia-2.3.4.vsix

Fix verification
![image](https://user-images.githubusercontent.com/30693990/162623576-22d10104-acbf-404b-97be-a36bd3130a0f.png)
