### ISSUE TITLE
Update to 1.0.0 - Error: Cannot find module 'typescript'

### ISSUE THREAD

**Issue by enrico-padovani** [aurelia/vscode-extension#70]
**I'm submitting a bug report**

* **Extension Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Visual studio code version:**
1.19.3

**Error** 
![untitled](https://user-images.githubusercontent.com/7766472/35443293-e3dd846e-02aa-11e8-8c6d-3da6c90938c8.png)
 at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\padovani.enrico\.vscode\extensions\AureliaEffect.aurelia-1.0.0\dist\src\server\FileParser\ProcessFiles.js:12:22)
    at Object.<anonymous> (C:\Users\padovani.enrico\.vscode\extensions\AureliaEffect.aurelia-1.0.0\dist\src\server\FileParser\ProcessFiles.js:184:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
[Error - 15:04:09] Connection to server got closed. Server will not be restarted.

**Comment by Jule-** [comment]
Same here!
I do not know about you @enrico-padovani but I am on `VS Code - Insiders`, maybe it is linked.

**Comment by enrico-padovani** [comment]
No @Jule, I've the "blue" version :)

**Comment by Jule-** [comment]
Yeah I have just seen your version... Mine is `1.20.0-insider`. ;)

**Comment by maroy1986** [comment]
Same here, VSCode version 1.19.3.

**Comment by eriklieben** [comment]
@maroy1986 thank you for the fix!

This issue should be resolved in the latest release (v1.0.1)
