### ISSUE TITLE
Error with view model intellisense

### ISSUE THREAD

**Issue by bigopon** [aurelia/vscode-extension#74]
I do not know why the error happen and I could not see any information related to document being parsed in the stack. I guess maybe some info where it starts to fail would be great, below is the log I got

```
smart auto complete init
C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\dist\src\server\FileParser\HTMLDocumentParser.js:67
        this.startOffset = location.startOffset;
                                   ^

TypeError: Cannot read property 'startOffset' of undefined
    at new AttributeDefinition (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\dist\src\server\FileParser\HTMLDocumentParser.js:67:36)
    at stack.push.attrs.map.i (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\dist\src\server\FileParser\HTMLDocumentParser.js:14:128)
    at Array.map (native)
    at module.exports.parser.on (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\dist\src\server\FileParser\HTMLDocumentParser.js:14:119)
    at emitMany (events.js:127:13)
    at module.exports.emit (events.js:204:7)
    at module.exports.SAXParser._handleToken (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\parse5\lib\sax\index.js:101:14)
    at module.exports.SAXParser._runParsingLoop (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\parse5\lib\sax\index.js:91:18)
    at module.exports.SAXParser._transform (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\parse5\lib\sax\index.js:45:14)
    at module.exports.Transform._read (_stream_transform.js:167:10)
[Info  - 07:30:01] Connection to server got closed. Server will restart.
[Error - 07:30:01] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\lib\client.js:1864:38)
	at LanguageClient.handleConnectionClosed (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\lib\main.js:106:15)
	at closeHandler (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\lib\client.js:1852:18)
	at CallbackList.invoke (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\lib\events.js:135:36)
smart auto complete init
C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\dist\src\server\FileParser\HTMLDocumentParser.js:67
        this.startOffset = location.startOffset;
                                   ^

TypeError: Cannot read property 'startOffset' of undefined
    at new AttributeDefinition (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\dist\src\server\FileParser\HTMLDocumentParser.js:67:36)
    at stack.push.attrs.map.i (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\dist\src\server\FileParser\HTMLDocumentParser.js:14:128)
    at Array.map (native)
    at module.exports.parser.on (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\dist\src\server\FileParser\HTMLDocumentParser.js:14:119)
    at emitMany (events.js:127:13)
    at module.exports.emit (events.js:204:7)
    at module.exports.SAXParser._handleToken (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\parse5\lib\sax\index.js:101:14)
    at module.exports.SAXParser._runParsingLoop (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\parse5\lib\sax\index.js:91:18)
    at module.exports.SAXParser._transform (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\parse5\lib\sax\index.js:45:14)
    at module.exports.Transform._read (_stream_transform.js:167:10)
[Info  - 07:30:03] Connection to server got closed. Server will restart.
[Error - 07:30:03] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\lib\client.js:1864:38)
	at LanguageClient.handleConnectionClosed (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\lib\main.js:106:15)
	at closeHandler (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\lib\client.js:1852:18)
	at CallbackList.invoke (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\lib\events.js:135:36)
smart auto complete init
C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\dist\src\server\FileParser\HTMLDocumentParser.js:67
        this.startOffset = location.startOffset;
                                   ^

TypeError: Cannot read property 'startOffset' of undefined
    at new AttributeDefinition (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\dist\src\server\FileParser\HTMLDocumentParser.js:67:36)
    at stack.push.attrs.map.i (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\dist\src\server\FileParser\HTMLDocumentParser.js:14:128)
    at Array.map (native)
    at module.exports.parser.on (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\dist\src\server\FileParser\HTMLDocumentParser.js:14:119)
    at emitMany (events.js:127:13)
    at module.exports.emit (events.js:204:7)
    at module.exports.SAXParser._handleToken (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\parse5\lib\sax\index.js:101:14)
    at module.exports.SAXParser._runParsingLoop (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\parse5\lib\sax\index.js:91:18)
    at module.exports.SAXParser._transform (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\parse5\lib\sax\index.js:45:14)
    at module.exports.Transform._read (_stream_transform.js:167:10)
[Info  - 07:30:04] Connection to server got closed. Server will restart.
[Error - 07:30:04] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\lib\client.js:1864:38)
	at LanguageClient.handleConnectionClosed (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\lib\main.js:106:15)
	at closeHandler (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\lib\client.js:1852:18)
	at CallbackList.invoke (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\vscode-languageclient\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\lib\events.js:135:36)
smart auto complete init
C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\dist\src\server\FileParser\HTMLDocumentParser.js:67
        this.startOffset = location.startOffset;
                                   ^

TypeError: Cannot read property 'startOffset' of undefined
    at new AttributeDefinition (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\dist\src\server\FileParser\HTMLDocumentParser.js:67:36)
    at stack.push.attrs.map.i (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\dist\src\server\FileParser\HTMLDocumentParser.js:14:128)
    at Array.map (native)
    at module.exports.parser.on (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\dist\src\server\FileParser\HTMLDocumentParser.js:14:119)
    at emitMany (events.js:127:13)
    at module.exports.emit (events.js:204:7)
    at module.exports.SAXParser._handleToken (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\parse5\lib\sax\index.js:101:14)
    at module.exports.SAXParser._runParsingLoop (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\parse5\lib\sax\index.js:91:18)
    at module.exports.SAXParser._transform (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\parse5\lib\sax\index.js:45:14)
    at module.exports.Transform._read (_stream_transform.js:167:10)
[Info  - 07:30:05] Connection to server got closed. Server will restart.
smart auto complete init
C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\dist\src\server\FileParser\HTMLDocumentParser.js:67
        this.startOffset = location.startOffset;
                                   ^

TypeError: Cannot read property 'startOffset' of undefined
    at new AttributeDefinition (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\dist\src\server\FileParser\HTMLDocumentParser.js:67:36)
    at stack.push.attrs.map.i (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\dist\src\server\FileParser\HTMLDocumentParser.js:14:128)
    at Array.map (native)
    at module.exports.parser.on (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\dist\src\server\FileParser\HTMLDocumentParser.js:14:119)
    at emitMany (events.js:127:13)
    at module.exports.emit (events.js:204:7)
    at module.exports.SAXParser._handleToken (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\parse5\lib\sax\index.js:101:14)
    at module.exports.SAXParser._runParsingLoop (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\parse5\lib\sax\index.js:91:18)
    at module.exports.SAXParser._transform (C:\Users\bigopon\.vscode-insiders\extensions\AureliaEffect.aurelia-1.0.1\node_modules\parse5\lib\sax\index.js:45:14)
    at module.exports.Transform._read (_stream_transform.js:167:10)
[Error - 07:30:07] Connection to server got closed. Server will not be restarted.

```

**Comment by eriklieben** [comment]
Thanks! Fixed.

I've should have written unit tests instead of cowboy coding this :-)

**Comment by bigopon** [comment]
@eriklieben cowboy is cool as long as you fix it promptly like this 👍 😄
